#!/bin/sh

PRODUCT_NAME=$1

generate_post_data()
{
  cat <<EOF
{
  "name": "$PRODUCT_NAME"
}
EOF
}

#echo "=================================================="
#echo "$(generate_post_data)"
#echo "=================================================="

#curl -i \
curl \
     --header "Accept:application/json" \
     --header "Content-Type:application/json" \
     --data "$(generate_post_data)" \
     "http://localhost:5050/product"
